### ISSUE TITLE
Very nice!

### ISSUE THREAD

**Issue by ritchiecarroll** [asty-org/asty#6]
Question, in most of all of the exports I've examined, the JSON result for `FileNode.Imports` is `null`, was this an intentional design decision (since the imports already exist in the main `File.Decls` hierarchy) or is this technically a bug?

Thanks!
Ritchie

**Comment by Evgenus** [comment]
Hi. Thanks for your issue. Sorry for the late reply.

> was this an intentional design decision (since the imports already exist in the main File.Decls hierarchy) or is this technically a bug?

Somewhat both. Yes,  you can find the imports list inside of declaration specs. Is there a case when you need it separately? It seems like golang itself can reconstruct sources without flaws even without it. I will prepare PR with `Imports` included so you can check if it works better.

**Comment by Evgenus** [comment]
@ritchiecarroll https://github.com/asty-org/asty/pull/8 you can try it if you need. My impression - it makes JSON significantly larger without apparent benefit. But, for the sake of completeness, we can include it.

**Comment by ritchiecarroll** [comment]
Wow, thanks so much! Personally, I do see value in having this from the perspective of completeness in a deserialized model - easier to just jump there and check for imports in that array.

Thanks again for such a nice tool.

**Comment by Evgenus** [comment]
@ritchiecarroll I think I pleased us both. I added another parameter to CLI `--imports` (default is false) which includes the list of imports to output JSON. Cheers.
